application: morphological-analysis
version: v1
runtime: python27
api_version: 1
threadsafe: true

instance_class: F2

handlers:
- url: /.*
  script: main.app

env_variables:
  USER_DICTIONARY: gs://morphological-analysis.appspot.com/dic/userdic.csv
